### ISSUE TITLE
BetterDiscord takes up over 1gb of RAM when clicking on enough channels [Bug]

### ISSUE THREAD

**Issue by Ommooo3** [BetterDiscord/BetterDiscord#1311]
**Describe the Bug**
Clicking on channels over-time raises my memory usage by around 20-70MB per channel and doesn't stop. With BetterDiscord uninstalled and replicating the same bug, Discord only takes up to 600MB, no higher. With BetterDiscord installed, this limit is overridden and Discord can end up taking up over 1GB of RAM just by using Discord casually within an hour or two (assuming you're using servers). Once it hits near 1.2GB/1.5GB of RAM used, BetterDiscord crashes entirely. I've had Discord crash consistently for the past two weeks because of this bug, and my only 'workaround' is to reload Discord when it starts being slow, but this shouldn't be occurring in the first place and sometimes I still crash anyway regardless of reloading. This also impacts my game performance because of the RAM usage from Discord alone.

**To Reproduce**
Go into any server, and quickly swap between all available channels in a server with Task Manager open. You should see the RAM usage raise up until eventually it hits around 1.2-1.5GB and crashes.

**Expected Behavior**
RAM usage should not be this high, it should be capped at around 600MB like regular Discord does.

**Screenshots**
![image](https://user-images.githubusercontent.com/45515626/170992189-232283ea-90a0-48f2-85c4-739958795b66.png)

**Discord Version**
Stable BetterDiscord 1.5.3, 1.6.0, 1.6.1, 1.6.2. Possibly earlier, don't know.
Happens on Canary too

**Additional Context**
Tried with no plugins enabled, no themes enabled (even restarting Discord entirely after disabling plugins/themes to ensure nothing is wrong). Tested with BetterDiscord uninstalled, and the issue does not occur.
Tested with hardware acceleration on and off, no difference.

**Comment by LilliPJs** [comment]
Happens to me as well, that would explain all the crashes have been occurring. Feels like content is being loaded into memory but not cleared fast enough, causing a buildup and then to an eventual crash

**Comment by OMAR-3OOV** [comment]
Maybe it depends on how many plugins you use, but it happen with me as well.

**Comment by ggtylerr** [comment]
> Maybe it depends on how many plugins you use, but it happen with me as well.
"Tried with no plugins enabled, no themes enabled (even restarting Discord entirely after disabling plugins/themes to ensure nothing is wrong)."

**Comment by SuperKirbylover** [comment]
this has been happening to me as well!! i've noticed that as i go through servers and channels, it takes much much longer to load each time. it's incredibly annoying

**Comment by Daxorinator** [comment]
Able to replicate this issue under the same circumstances described by the OP.

**Comment by TaakoOfficial** [comment]
I too have been having this issue

**Comment by GaiaB0t** [comment]
> Happens to me as well, that would explain all the crashes have been occurring. Feels like content is being loaded into memory but not cleared fast enough, causing a buildup and then to an eventual crash

I agree with this

**Comment by Luke2919** [comment]
This also happens to me it's mad annoying

**Comment by Infinitay** [comment]
This wouldn't happen to explain why BD feels sluggish on first loads would it? Specifically, when I first get on Discord and despite plugins has finished loading; when I click on a channel Discord lags for 1-3 seconds but doesn't switch to the channel. I have to click it a second time for it to go through.

This also rarely happens throughout the day after some long period of time. A CTRL+R fixes this and stops the _sluggishness_.

**Comment by rauenzi** [comment]
Many crashing, memory, and cpu issues have been fixed with the latest update.

**Comment by Ommooo3** [comment]
> Many crashing, memory, and cpu issues have been fixed with the latest update.

My issue still occurs on BetterDiscord 1.8.2 - after a few hours of regular usage, Discord will still take over 1.5gb of RAM and function incredibly slowly, until it eventually crashes. Doesn't matter if I disable all plugins or not.
![image](https://user-images.githubusercontent.com/45515626/197217982-46d6dc9e-6419-496d-aba8-250cc384f700.png)

**Comment by xDidntPot** [comment]
> > Many crashing, memory, and cpu issues have been fixed with the latest update.
> 
> My issue still occurs on BetterDiscord 1.8.2 - after a few hours of regular usage, Discord will still take over 1.5gb of RAM and function incredibly slowly, until it eventually crashes. Doesn't matter if I disable all plugins or not. ![image](https://user-images.githubusercontent.com/45515626/197217982-46d6dc9e-6419-496d-aba8-250cc384f700.png) ![image](https://user-images.githubusercontent.com/45515626/197218581-dafa2b72-deb7-4ff9-9c9d-3960f2ce043b.png)

Literally the same is happening with me.

**Comment by Decimation** [comment]
Same problem here.

**Comment by Aholicknight** [comment]
Having the same problem as well

**Comment by CachorroVoador** [comment]
Me too!

**Comment by santiagocss** [comment]
Stop saying you have the same problem.

**Comment by Aholicknight** [comment]
> Stop saying you have the same problem.

![SystemInformer_20221122_hPrz8QPKHa](https://user-images.githubusercontent.com/7843719/203469977-0cb4466c-a8ea-4fab-8a17-ab49a3cf4111.png)

@santiagocss I do tho?

**Comment by OMAR-3OOV** [comment]
> > Stop saying you have the same problem.
> 
> ![SystemInformer_20221122_hPrz8QPKHa](https://user-images.githubusercontent.com/7843719/203469977-0cb4466c-a8ea-4fab-8a17-ab49a3cf4111.png)
> 
> @santiagocss I do tho?

bro 799mb is nothing according to normal discord, but some people face high ram like 1.5gb and higher and low plugins and none theme uses!

**Comment by KarlGhartler** [comment]
I have a whopping 2 plugins and it regularly goes up to 1gb or more

**Comment by ramseyspace** [comment]
Mines already hit 1.5gb of RAM usage today, seems a bit excessive and yes got 6 sections underneath discord in task manager. Also, the discord streaming takes up 25% of my gpu and got 5070ti so something feels off.
