### ISSUE TITLE
[Bug] cannot record keybind

### ISSUE THREAD

**Issue by ShadowCreator250** [BetterDiscord/BetterDiscord#1686]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

When I try to set a keybind it stays at `[object Undefined]`

### Expected Behavior

it should record my typed in keybind and save it

### Steps To Reproduce

discord version: Stable 240884 (d20955f) Host 1.0.9021 x86 (38954) Windows 10 64-Bit (10.0.19045)
1. go to settings
2. got to keybinds tab
3. click on `add a keybind`
4. set action to eg `toggle mute` and try to record the keybind `Ctrl + Alt + N`

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.9.5

### Anything else?

![grafik](https://github.com/BetterDiscord/BetterDiscord/assets/52125935/9b19aad7-774f-44f0-90a9-cfeb0e4ce821)

**Comment by fowlis** [comment]
Does this only happen while BetterDiscord is installed? Have you tried uninstalling it and seeing what happens on normal Discord?

**Comment by ShadowCreator250** [comment]
> Does this only happen while BetterDiscord is installed? Have you tried uninstalling it and seeing what happens on normal Discord?

Yup, I uninstalled BetterDiscord and now it works:
![grafik](https://github.com/BetterDiscord/BetterDiscord/assets/52125935/6748e921-9568-4fb6-b95e-e850a7e4488b)

Also: the `[object Undefined]` would appear, when no keybind was set. With vanilla Discord, that isn't the case anymore:
![grafik](https://github.com/BetterDiscord/BetterDiscord/assets/52125935/f3fd8b66-2414-405b-9ce5-b8e7aa472f5c)

**Comment by rauenzi** [comment]
I already have a fix locally, it'll be included in next version.

Note: This only affects the _display_ of the keybind, actual setting and using of the keybinds is unaffected.

**Comment by ShadowCreator250** [comment]
> I already have a fix locally, it'll be included in next version.
> 
> Note: This only affects the _display_ of the keybind, actual setting and using of the keybinds is unaffected.

That's great news! Thanks for clarifying! Tbh I did not even check that.

**Comment by IIIdefconIII** [comment]
> > I already have a fix locally, it'll be included in next version.
> > Note: This only affects the _display_ of the keybind, actual setting and using of the keybinds is unaffected.
> 
> That's great news! Thanks for clarifying! Tbh I did not even check that.

HI man, got any update about this? I also stept over to BetterDiscord, for the first time now. But also having the object undigined isuse

**Comment by rauenzi** [comment]
Yes it will be released very soon

**Comment by rauenzi** [comment]
Fixed in the new release

**Comment by kryloxgd** [comment]
bug is still present in the linux release just btw
doesnt even record a keybind it just constantly says no keybind set even if you try to set one

**Comment by zerebos** [comment]
This is an issue from 3 years ago, it is extremely likely a different bug.
