### ISSUE TITLE
[Bug] Setting "Remove Minimum Size" does not work

### ISSUE THREAD

**Issue by thiago-negri** [BetterDiscord/BetterDiscord#1885]
### Before Reporting

- [x] I found no existing issues matching my bug
- [x] My issue is not caused by a plugin or theme

### Describe the Bug

Enabling "Remove Minimum Size" doesn't do anything for me. Even after restarting discord.

### Expected Behavior

I'd like to have a small window, without the chat.

### Steps To Reproduce

I just installed Better Discord, and toggled "Remove Minimum Size".

Also tried adding MIN_WIDTH and MIN_HEIGHT to `%appdata%/discord/settings.json` but that didn't work either.

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.12.1

### Anything else?

I found this bug but it's closed: https://github.com/BetterDiscord/BetterDiscord/issues/1773

**Comment by doggybootsy** [comment]
Restarting Discord twice should fix it

**Comment by STR4NG3RdotSH** [comment]
Disregard my response. Despite ALT+F4-ing to close discord, it remained open in processes. Killing any/all discord processes (`for x in $(pgrep Discord); do kill -9 $x; done`) and re-launching fixed it. 

This may be the case for @thiago-negri as well, albeit in windows. Check your task manager and end task any discord processes.

**Comment by thiago-negri** [comment]
It doesn't work even after restarting the PC.

**Comment by kilmameri** [comment]
I have had the same issue for two days now. It started after I got the newest discord update

**Comment by Giblet4961** [comment]
Same issue. I've disabled and re-enabled the setting. I've confirmed that it changes the min width/height settings to 0 in the settings.json file. Going into task manager -> details -> killing all instances of discord + rebooting discord doesn't work. 


Discord: stable 382355 (e3770fd) 
BD: stable 1.12.1

**Comment by RyuTechDE** [comment]
I did encounter the issue also however when setting free window size to "OFF" it will work temporarly after the restart for some reason. 

If now however you resize the window again after the first resize that worked it will "snap" back to its minimum original size and refuses to go any smaller until you repeat the process of turning it on -> restarting -> turning it off -> restarting

Something resets whatever the option is doing during use. And the fact that turning off the option turns is on is also there.

I hope this will be fixed soon o7

**Comment by Obbama** [comment]
Issue persisting. Meanwhile you can edit the json file for discord to have your desired fixed size when it starts up, but any resizing and it snaps back to the min size.

**Comment by h-sigma** [comment]
Any news?

**Comment by knksng0504** [comment]
This bug does not appear to have been fixed in today's update.

**Comment by knksng0504** [comment]
This bug continues to occur after applying today's update.
We hope it will be fixed soon.

**Comment by aunight** [comment]
still not work no matter I reinstall discord and betterdiscord
No any funtion to reset the setting?

**Comment by SeraphimOfTines** [comment]
We rely on this feature to position our windows correctly. We love your work on BD! We're hoping this can be fixed soon too! We've tried the above fixes posted in this thread as well, and its still broken. :(

**Comment by Giblet4961** [comment]
> We rely on this feature to position our windows correctly. We love your work on BD! We're hoping this can be fixed soon too! We've tried the above fixes posted in this thread as well, and its still broken. :(

The other popular discord mod app still has functioning 'remove minimum size'. Unfortunately doesn't have all the plug-ins I need, but worth using in the meantime. Not sure if I'm allowed to mention it, so DM me if you can't find it.

**Comment by thiago-negri** [comment]
What's the alternative? Of course you can comment here

**Comment by Giblet4961** [comment]
> What's the alternative? Of course you can comment here

Vencord. Uninstall BD first, install Vencord. Enable 'remove minimum size' in settings

**Comment by zerebos** [comment]
Would anyone here be willing to test a private fix for this?

**Comment by aunight** [comment]
@zerebos  Me

**Comment by zerebos** [comment]
To test this private fix, make sure you have enabled the `Remove Minimum Size` option in BetterDiscord's settings. Then do the following:

1. Fully exit/close Discord so it's no longer running.
2. Locate `betterdiscord.asar`, it should be in the BetterDiscord folder like `%appdata%/BetterDiscord/data/betterdiscord.asar`
3. Download the `betterdiscord.asar` from here: https://cdn.discordapp.com/attachments/341062370627682315/1381383340300439612/betterdiscord.asar?ex=684750fd&is=6845ff7d&hm=48a32a92b974ea43030c154496e64e96a9849f21fea20b96e5063ae74698d2f3&
4. Replace the `asar` file in step 2 with the one downloaded in step 3
5. Launch Discord
6. It works???

**Comment by SeraphimOfTines** [comment]
That works perfectly! Thank you!

**Comment by OnyxL** [comment]
> To test this private fix, make sure you have enabled the `Remove Minimum Size` option in BetterDiscord's settings. Then do the following:
> 
> 1. Fully exit/close Discord so it's no longer running.
> 2. Locate `betterdiscord.asar`, it should be in the BetterDiscord folder like `%appdata%/BetterDiscord/data/betterdiscord.asar`
> 3. Download the `betterdiscord.asar` from here: https://cdn.discordapp.com/attachments/341062370627682315/1381383340300439612/betterdiscord.asar?ex=684750fd&is=6845ff7d&hm=48a32a92b974ea43030c154496e64e96a9849f21fea20b96e5063ae74698d2f3&
> 4. Replace the `asar` file in step 2 with the one downloaded in step 3
> 5. Launch Discord
> 6. It works???

the link not working anymore?

**Comment by martincutcher** [comment]
Does anyone have the fixed asar file?

**Comment by Giblet4961** [comment]
Still no resolution to this one?

**Comment by martincutcher** [comment]
> Still no resolution to this one?

They fixed it in the new version

**Comment by Giblet4961** [comment]
> > Still no resolution to this one?
> 
> They fixed it in the new version

Thank you!
